function [] = plot_1_sample_traces (dir,visDrivenIDX,traces,visstimTrace,plotPack)


  
    %visDrivenNeurons=find(any(visDrivenIDX,2));
    for i=1:size(visDrivenIDX,1)
        if any(visDrivenIDX(i,:))
            
        [filename,plotTitle,plotInfo]=gen_plot_info ...
                    (plotPack.runName, ...
                    plotPack.runFilename, ...
                    i, ...
                    [fixedInfo  datestr(now)], ...
                    plotPack.fixedTitle, ...
                    plotPack.oriStr, ...
                    visDrivenIDX(i,:), ...
                    plotPack.statsp(i,:));
                
        % analysis
        traces_vis(dir,traces(i,:),lim,vistimTrace, ...
                       visDrivenIDX(i,:),filename,plotTitle,plotInfo,plotPack.oriStr);
        ends
    end

end